# Welcome to Jekyll Paper for Github
#
# This is the configuration file for your blog, please change these items after forked.

title: Daniel Sprague
email: d.a.sprague@outlook.com
name: Daniel Sprague
description: >- # this means to ignore newlines until "baseurl:"
  I am a computational biologist, machine learning researcher, Bayesian enthusiast, and Julia evangelist. This website contains thoughts on biological machine learning, data science, and programming. Links to my projects and publications can be found in the menu above. Thanks for visiting!
keywords: biology, computational biology, machine learning, data science, programming
baseurl: '' # the subpath of your site, e.g. /`blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
domain: 'example.com' # the domain name for your site, e.g. example.com
language: en
timezone: America/New_York

analytics: # the Google Analytics property ID, e.g. UA-XXXXX-Y

comments: false # enable comments
disqus: # disqus account

mathjax: true # Math support
diagram: true # Diagrams support

paginate: 25
paginate_path: '/page:num/'

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
